<?php

namespace App\Actions\Samples;

use App\BuildingBlocks\Actions\Action;
use App\BuildingBlocks\Actions\ActionCapabilities;
use Route;

class SampleAction extends GeneratedSampleAction implements Action
{
    use ActionCapabilities {
        ActionCapabilities::validationRules as private defaultRules;
    }

    public static function fields(array $payload): array
    {
        // TODO: Modify or replace the autogenerated fields
        parent::fields($payload);
    }

    public static function routes(): void
    {
        // TODO: Implement routes
        // Route::get('/api/business/', self::class)
        //    ->name('business.get')
        //;
    }

    public function authorize(array $payload): bool
    {
        return true;
    }

    public function validationRules(array $payload): array
    {
        // TODO: Modify or replace the autogenerated validation rules
        return $this->defaultRules($payload);
    }
}
